let dados = [
  {
    nome: "Athletico-PR",
    descricao:
      "O Club Athletico Paranaense é um dos grandes clubes do futebol brasileiro, conhecido por sua moderna arena e conquistas nacionais e internacionais.",
    fundacao: "26-03-1924",
    estadio: "Arena da Baixada",
    site_oficial: "https://www.athletico.com.br/",
    tags: "athletico-pr, furacão, arena da baixada, futebol paranaense, serie a, campeonato paranaense, vermelho, preto",
    serie: "A",
    logo: "logos/cap.png",
  },
  {
    nome: "Atlético-GO",
    descricao:
      "O Atlético Clube Goianiense, também conhecido como Dragão, é um dos principais clubes de Goiás, com várias conquistas regionais.",
    fundacao: "02-04-1937",
    estadio: "Estádio Antônio Accioly",
    site_oficial: "https://www.atleticogoianiense.com.br/",
    tags: "atlético-go, dragão, futebol goiano, estádio antônio accioly, serie a, campeonato goiano, vermelho, preto",
    serie: "A",
    logo: "logos/atlgo.png",
  },
  {
    nome: "Atlético-MG",
    descricao:
      "O Atlético Mineiro, conhecido como Galo, é um dos clubes mais tradicionais de Minas Gerais, com uma história repleta de conquistas e uma torcida apaixonada.",
    fundacao: "25-03-1908",
    estadio: "Mineirão",
    site_oficial: "https://www.atletico.com.br/",
    tags: "atlético mineiro, galo, mineirão, futebol mineiro, serie a, campeonato mineiro, preto, branco",
    serie: "A",
    logo: "logos/cam.svg",
  },
  {
    nome: "Bahia",
    descricao:
      "O Esporte Clube Bahia é um dos maiores clubes do Nordeste brasileiro, com uma torcida fervorosa e várias conquistas nacionais.",
    fundacao: "01-01-1931",
    estadio: "Arena Fonte Nova",
    site_oficial: "https://www.esporteclubebahia.com.br/",
    tags: "bahia, esquadrão de aço, futebol nordestino, arena fonte nova, serie a, campeonato baiano, azul, vermelho",
    serie: "A",
    logo: "logos/bah.png",
  },
  {
    nome: "Botafogo",
    descricao:
      "O Botafogo de Futebol e Regatas é um dos clubes mais tradicionais do Brasil, com uma história de títulos e uma torcida apaixonada.",
    fundacao: "12-08-1904",
    estadio: "Estádio Nilton Santos",
    site_oficial: "https://www.botafogo.com.br/",
    tags: "botafogo, glorioso, estádio nilton santos, futebol carioca, serie a, campeonato carioca, preto, branco",
    serie: "A",
    logo: "logos/bot.png",
  },
  {
    nome: "Bragantino",
    descricao:
      "O Red Bull Bragantino é um clube em ascensão no futebol brasileiro, apoiado pelo grupo Red Bull, com um projeto inovador.",
    fundacao: "08-01-1928",
    estadio: "Estádio Nabi Abi Chedid",
    site_oficial: "https://www.redbullbragantino.com.br/",
    tags: "bragantino, red bull, estádio nabi abi chedid, futebol paulista, serie a, campeonato paulista, vermelho, branco",
    serie: "A",
    logo: "logos/bra.svg",
  },
  {
    nome: "Corinthians",
    descricao:
      "O Sport Club Corinthians Paulista é um dos maiores clubes do Brasil, com uma imensa torcida e uma história de grandes conquistas.",
    fundacao: "01-09-1910",
    estadio: "Neo Química Arena",
    site_oficial: "https://www.corinthians.com.br/",
    tags: "corinthians, timão, neo química arena, futebol paulista, serie a, campeonato paulista, preto, branco",
    serie: "A",
    logo: "logos/cor.png",
  },
  {
    nome: "Criciúma",
    descricao:
      "O Criciúma Esporte Clube é um dos principais clubes de Santa Catarina, com conquistas importantes em competições nacionais.",
    fundacao: "13-05-1947",
    estadio: "Estádio Heriberto Hülse",
    site_oficial: "https://www.criciuma.com.br/",
    tags: "criciúma, tigre, estádio heriberto hülse, futebol catarinense, serie a, campeonato catarinense, amarelo, preto",
    serie: "A",
    logo: "logos/cri.png",
  },
  {
    nome: "Cruzeiro",
    descricao:
      "O Cruzeiro Esporte Clube é um dos grandes clubes do futebol brasileiro, com conquistas nacionais e internacionais.",
    fundacao: "02-01-1921",
    estadio: "Mineirão",
    site_oficial: "https://www.cruzeiro.com.br/",
    tags: "cruzeiro, raposa, mineirão, futebol mineiro, serie a, campeonato mineiro, azul, branco",
    serie: "A",
    logo: "logos/cru.png",
  },
  {
    nome: "Cuiabá",
    descricao:
      "O Cuiabá Esporte Clube é um dos clubes mais promissores do Centro-Oeste brasileiro, com crescente relevância no cenário nacional.",
    fundacao: "12-12-2001",
    estadio: "Arena Pantanal",
    site_oficial: "https://www.cuiabaesporteclube.com.br/",
    tags: "cuiabá, dourado, arena pantanal, futebol mato-grossense, serie a, campeonato mato-grossense, verde, amarelo",
    serie: "A",
    logo: "logos/cuiaba.png",
  },
  {
    nome: "Flamengo",
    descricao:
      "O Clube de Regatas do Flamengo é um dos maiores clubes do Brasil, com uma torcida apaixonada e uma história repleta de títulos nacionais e internacionais.",
    fundacao: "17-11-1895",
    estadio: "Maracanã",
    site_oficial: "https://www.flamengo.com.br/",
    tags: "flamengo, mengo, clube de regatas, rubro-negro, maracanã, futebol carioca, serie a, campeonato carioca, vermelho, preto",
    serie: "A",
    logo: "logos/fla.png",
  },
  {
    nome: "Fluminense",
    descricao:
      "O Fluminense Football Club é um dos mais tradicionais clubes do Brasil, com uma rica história de títulos e uma torcida fiel.",
    fundacao: "21-07-1902",
    estadio: "Maracanã",
    site_oficial: "https://www.fluminense.com.br/",
    tags: "fluminense, flu, tricolor, maracanã, futebol carioca, serie a, campeonato carioca, verde, branco",
    serie: "A",
    logo: "logos/flu.svg",
  },
  {
    nome: "Fortaleza",
    descricao:
      "O Fortaleza Esporte Clube é um dos clubes mais importantes do Nordeste brasileiro, com uma torcida apaixonada e conquistas recentes.",
    fundacao: "18-10-1918",
    estadio: "Arena Castelão",
    site_oficial: "https://www.fortalezaec.net/",
    tags: "fortaleza, leão, castelão, futebol nordestino, serie a, campeonato cearense, vermelho, azul",
    serie: "A",
    logo: "logos/for.png",
  },
  {
    nome: "Grêmio",
    descricao:
      "O Grêmio Foot-Ball Porto Alegrense é um dos grandes clubes do Brasil, com diversas conquistas nacionais e internacionais.",
    fundacao: "15-09-1903",
    estadio: "Arena do Grêmio",
    site_oficial: "https://www.gremio.net/",
    tags: "grêmio, tricolor, arena do grêmio, futebol gaúcho, serie a, campeonato gaúcho, azul, preto, branco",
    serie: "A",
    logo: "logos/gremio.png",
  },
  {
    nome: "Internacional",
    descricao:
      "O Sport Club Internacional, conhecido como Colorado, é um dos maiores clubes do Brasil, com uma história repleta de conquistas internacionais.",
    fundacao: "04-04-1909",
    estadio: "Beira-Rio",
    site_oficial: "https://www.internacional.com.br/",
    tags: "internacional, colorado, beira-rio, futebol gaúcho, serie a, campeonato gaúcho, vermelho, branco",
    serie: "A",
    logo: "logos/inter.png",
  },
  {
    nome: "Juventude",
    descricao:
      "O Esporte Clube Juventude é um clube tradicional do futebol gaúcho, com títulos regionais e participação em competições nacionais.",
    fundacao: "29-06-1913",
    estadio: "Estádio Alfredo Jaconi",
    site_oficial: "https://www.juventude.com.br/",
    tags: "juventude, alviverde, estádio alfredo jaconi, futebol gaúcho, serie a, campeonato gaúcho, verde, branco",
    serie: "A",
    logo: "logos/juv.png",
  },
  {
    nome: "Palmeiras",
    descricao:
      "A Sociedade Esportiva Palmeiras é um dos clubes mais tradicionais do Brasil, com inúmeros títulos nacionais e uma forte presença no futebol sul-americano.",
    fundacao: "26-08-1914",
    estadio: "Allianz Parque",
    site_oficial: "https://www.palmeiras.com.br/",
    tags: "palmeiras, verdão, palestra, allianz parque, futebol paulista, serie a, campeonato paulista, verde, branco",
    serie: "A",
    logo: "logos/pal.png",
  },
  {
    nome: "São Paulo",
    descricao:
      "O São Paulo Futebol Clube é um dos clubes mais vitoriosos do Brasil, com uma rica história de conquistas nacionais e internacionais.",
    fundacao: "25-01-1930",
    estadio: "Morumbi",
    site_oficial: "https://www.saopaulofc.net/",
    tags: "são paulo, tricolor paulista, morumbi, futebol paulista, serie a, campeonato paulista, vermelho, preto, branco",
    serie: "A",
    logo: "logos/sao.png",
  },
  {
    nome: "Vasco",
    descricao:
      "O Club de Regatas Vasco da Gama é um dos clubes mais tradicionais do Brasil, com uma rica história de conquistas e uma grande torcida.",
    fundacao: "21-08-1898",
    estadio: "Estádio São Januário",
    site_oficial: "https://www.vasco.com.br/",
    tags: "vasco, cruzmaltino, são januário, futebol carioca, serie a, campeonato carioca, preto, branco",
    serie: "A",
    logo: "logos/vasco.png",
  },
  {
    nome: "América-MG",
    descricao:
      "O América Futebol Clube é um dos clubes tradicionais de Minas Gerais, com uma história rica e várias conquistas regionais.",
    fundacao: "30-04-1912",
    estadio: "Estádio Independência",
    site_oficial: "https://www.americamineiro.com.br/",
    tags: "américa-mg, coelho, estádio independência, futebol mineiro, serie b, campeonato mineiro, verde, branco",
    serie: "B",
    logo: "logos/Amemg.png",
  },
  {
    nome: "Avaí",
    descricao:
      "O Avaí Futebol Clube é um dos principais clubes de Santa Catarina, com uma torcida apaixonada e diversas conquistas regionais.",
    fundacao: "01-05-1923",
    estadio: "Estádio da Ressacada",
    site_oficial: "https://www.avai.com.br/",
    tags: "avaí, leão da ilha, estádio da ressacada, futebol catarinense, serie b, campeonato catarinense, azul, branco",
    serie: "B",
    logo: "logos/avai.png",
  },
  {
    nome: "Botafogo-SP",
    descricao:
      "O Botafogo Futebol Clube, conhecido como Botafogo-SP, é um dos clubes tradicionais de São Paulo, com uma história rica em títulos regionais.",
    fundacao: "01-07-1918",
    estadio: "Estádio Santa Cruz",
    site_oficial: "https://www.botafogosp.com.br/",
    tags: "botafogo-sp, pantera, estádio santa cruz, futebol paulista, serie b, campeonato paulista, preto, branco",
    serie: "B",
    logo: "logos/botsp.png",
  },
  {
    nome: "Brusque",
    descricao:
      "O Brusque Futebol Clube é um dos clubes emergentes de Santa Catarina, com uma crescente presença no cenário nacional.",
    fundacao: "08-09-1987",
    estadio: "Estádio Augusto Bauer",
    site_oficial: "https://www.bfc.com.br/",
    tags: "brusque, brusqueta, estádio augusto bauer, futebol catarinense, serie b, campeonato catarinense, branco, azul",
    serie: "B",
    logo: "logos/brus.png",
  },
  {
    nome: "Ceará",
    descricao:
      "O Ceará Sporting Club é um dos grandes clubes do Nordeste, com uma história rica e uma torcida apaixonada.",
    fundacao: "02-06-1914",
    estadio: "Arena Castelão",
    site_oficial: "https://www.cearasc.com.br/",
    tags: "ceará, vozão, arena castelão, futebol nordestino, serie b, campeonato cearense, preto, branco",
    serie: "B",
    logo: "logos/ceara.png",
  },
  {
    nome: "Chapecoense",
    descricao:
      "A Associação Chapecoense de Futebol é conhecida por sua trajetória emocionante e pela força de sua torcida.",
    fundacao: "10-05-1973",
    estadio: "Arena Condá",
    site_oficial: "https://www.chapecoense.com.br/",
    tags: "chapecoense, verdão, arena condá, futebol catarinense, serie b, campeonato catarinense, verde, branco",
    serie: "B",
    logo: "logos/chape.png",
  },
  {
    nome: "Coritiba",
    descricao:
      "O Coritiba Foot Ball Club é um dos clubes mais tradicionais do Paraná, com uma grande história e uma torcida apaixonada.",
    fundacao: "12-10-1909",
    estadio: "Estádio Couto Pereira",
    site_oficial: "https://www.coritiba.com.br/",
    tags: "coritiba, coxa, estádio couto pereira, futebol paranaense, serie b, campeonato paranaense, verde, branco",
    serie: "B",
    logo: "logos/coxa.png",
  },
  {
    nome: "CRB",
    descricao:
      "O Clube de Regatas Brasil é um dos principais clubes de Alagoas, com uma rica história de conquistas regionais.",
    fundacao: "20-09-1912",
    estadio: "Estádio Rei Pelé",
    site_oficial: "https://www.crb.esp.br/",
    tags: "crb, galo, estádio rei pelé, futebol alagoano, serie b, campeonato alagoano, vermelho, branco",
    serie: "B",
    logo: "logos/crb.png",
  },
  {
    nome: "Goiás",
    descricao:
      "O Goiás Esporte Clube é um dos clubes mais importantes de Goiás, com uma longa história de conquistas e uma grande torcida.",
    fundacao: "06-04-1943",
    estadio: "Estádio da Serrinha",
    site_oficial: "https://www.goiasec.com.br/",
    tags: "goiás, esmeraldino, estádio da serrinha, futebol goiano, serie b, campeonato goiano, verde, branco",
    serie: "B",
    logo: "logos/goias.png",
  },
  {
    nome: "Guarani",
    descricao:
      "O Guarani Futebol Clube é um dos clubes tradicionais de São Paulo, com uma rica história de títulos e uma torcida apaixonada.",
    fundacao: "01-04-1911",
    estadio: "Estádio Brinco de Ouro",
    site_oficial: "https://www.guarani.com.br/",
    tags: "guarani, bugre, estádio brinco de ouro, futebol paulista, serie b, campeonato paulista, verde, branco",
    serie: "B",
    logo: "logos/gua.png",
  },
  {
    nome: "Ituano",
    descricao:
      "O Ituano Futebol Clube é um dos clubes emergentes de São Paulo, com uma presença crescente no cenário nacional.",
    fundacao: "24-09-1947",
    estadio: "Estádio Novelli Júnior",
    site_oficial: "https://www.ituano.com.br/",
    tags: "ituano, galo, estádio novelli júnior, futebol paulista, serie b, campeonato paulista, vermelho, preto",
    serie: "B",
    logo: "logos/itu.png",
  },
  {
    nome: "Mirassol",
    descricao:
      "O Mirassol Futebol Clube é um dos clubes em ascensão do futebol paulista, com uma crescente presença nas competições nacionais.",
    fundacao: "29-12-1925",
    estadio: "Estádio Municipal José Maria de Campos Maia",
    site_oficial: "https://www.mirassolfc.com.br/",
    tags: "mirassol, leão, estádio municipal josé maria de campos maia, futebol paulista, serie b, campeonato paulista, amarelo, preto",
    serie: "B",
    logo: "logos/mira.png",
  },
  {
    nome: "Novorizontino",
    descricao:
      "O Grêmio Novorizontino é um clube em crescimento no futebol paulista, com um projeto de desenvolvimento contínuo.",
    fundacao: "01-05-1986",
    estadio: "Estádio Jorge Ismael de Biasi",
    site_oficial: "https://www.gnfc.com.br/",
    tags: "novorizontino, tigre, estádio jorge ismael de biasi, futebol paulista, serie b, campeonato paulista, amarelo, preto",
    serie: "B",
    logo: "logos/novo.png",
  },
  {
    nome: "Operário-PR",
    descricao:
      "O Operário Ferroviário Esporte Clube é um dos clubes tradicionais do Paraná, com uma história de títulos regionais e uma torcida fiel.",
    fundacao: "01-05-1912",
    estadio: "Estádio Germano Krüger",
    site_oficial: "https://www.operarioferroviario.com.br/",
    tags: "operário-pr, fantasma, estádio germano krüger, futebol paranaense, serie b, campeonato paranaense, preto, branco",
    serie: "B",
    logo: "logos/ope.png",
  },
  {
    nome: "Paysandu",
    descricao:
      "O Paysandu Sport Club é um dos clubes mais tradicionais do Pará, com uma história rica e uma torcida apaixonada.",
    fundacao: "02-02-1914",
    estadio: "Estádio da Curuzu",
    site_oficial: "https://www.paysandu.com.br/",
    tags: "paysandu, papão, estádio da curuzu, futebol paraense, serie b, campeonato paraense, azul, branco",
    serie: "B",
    logo: "logos/papao.png",
  },
  {
    nome: "Ponte Preta",
    descricao:
      "A Associação Atlética Ponte Preta é um dos clubes mais antigos e tradicionais de São Paulo, com uma rica história de títulos.",
    fundacao: "11-08-1900",
    estadio: "Estádio Moisés Lucarelli",
    site_oficial: "https://www.pontepreta.com.br/",
    tags: "ponte preta, macaca, estádio moisés lucarelli, futebol paulista, serie b, campeonato paulista, preto, branco",
    serie: "B",
    logo: "logos/ponte.png",
  },
  {
    nome: "Santos",
    descricao:
      "O Santos Futebol Clube é um dos clubes mais renomados do Brasil, com uma rica história de conquistas nacionais e internacionais.",
    fundacao: "14-04-1912",
    estadio: "Vila Belmiro",
    site_oficial: "https://www.santosfc.com.br/",
    tags: "santos, peixe, vila belmiro, futebol paulista, serie b, campeonato paulista, branco, preto",
    serie: "B",
    logo: "logos/santos.png",
  },
  {
    nome: "Sport",
    descricao:
      "O Sport Club do Recife é um dos grandes clubes do Nordeste, com uma rica história e uma torcida apaixonada.",
    fundacao: "13-05-1905",
    estadio: "Estádio Ilha do Retiro",
    site_oficial: "https://www.sportrecife.com.br/",
    tags: "sport, leão, estádio ilha do retiro, futebol nordestino, serie b, campeonato pernambucano, vermelho, preto",
    serie: "B",
    logo: "logos/sport.png",
  },
  {
    nome: "Vila Nova",
    descricao:
      "O Vila Nova Futebol Clube é um dos clubes tradicionais de Goiás, com uma história rica e uma torcida apaixonada.",
    fundacao: "09-07-1943",
    estadio: "Estádio Onésio Brasileiro Alvarenga",
    site_oficial: "https://www.vilanovafc.com.br/",
    tags: "vila nova, tigre, estádio onésio brasileiro alvarenga, futebol goiano, serie b, campeonato goiano, vermelho, branco",
    serie: "B",
    logo: "logos/vila.png",
  },
  {
    nome: "ABC",
    descricao:
      "O ABC Futebol Clube é um dos clubes mais tradicionais do futebol potiguar, com uma rica história de conquistas regionais.",
    fundacao: "29-06-1915",
    estadio: "Estádio Frasqueirão",
    site_oficial: "https://www.abcfc.com.br/",
    tags: "abc, abc fc, estádio frasqueirão, futebol potiguar, serie c, campeonato potiguar, vermelho, branco",
    serie: "C",
    logo: "logos/abc.png",
  },
  {
    nome: "Aparecidense",
    descricao:
      "A Associação Atlética Aparecidense é um clube de destaque em Goiás, com uma trajetória crescente no cenário nacional.",
    fundacao: "01-01-2000",
    estadio: "Estádio Aníbal Toledo",
    site_oficial: "https://www.aaparecidense.com.br/",
    tags: "aparecidense, aparecidense, estádio aníbal toledo, futebol goiano, serie c, campeonato goiano, vermelho, branco",
    serie: "C",
    logo: "logos/apa.png",
  },
  {
    nome: "Athletic Club",
    descricao:
      "O Athletic Club é um time tradicional de Minas Gerais, com uma história rica em competições regionais.",
    fundacao: "01-01-1915",
    estadio: "Estádio Antônio Guimarães",
    site_oficial: "https://www.athleticclub.com.br/",
    tags: "athletic club, athletic, estádio antônio guimarães, futebol mineiro, serie c, campeonato mineiro, vermelho, preto",
    serie: "C",
    logo: "logos/athl.png",
  },
  {
    nome: "Botafogo-PB",
    descricao:
      "O Botafogo Futebol Clube da Paraíba é um dos clubes mais tradicionais do estado, com uma rica história no futebol nordestino.",
    fundacao: "01-07-1931",
    estadio: "Estádio Almeidão",
    site_oficial: "https://www.botafogopb.com.br/",
    tags: "botafogo pb, botafogo paraíba, estádio almeidão, futebol nordestino, serie c, campeonato paraibano, preto, branco",
    serie: "C",
    logo: "logos/botpb.png",
  },
  {
    nome: "Caxias",
    descricao:
      "O Caxias Futebol Clube é um dos clubes mais tradicionais do Rio Grande do Sul, com uma rica história de conquistas regionais.",
    fundacao: "10-05-1910",
    estadio: "Estádio Centenário",
    site_oficial: "https://www.caxias.com.br/",
    tags: "caxias, caxias fc, estádio centenário, futebol gaúcho, serie c, campeonato gaúcho, vermelho, branco",
    serie: "C",
    logo: "logos/cax.png",
  },
  {
    nome: "CSA",
    descricao:
      "O Centro Sportivo Alagoano é um dos clubes de destaque em Alagoas, com uma rica história de conquistas e uma torcida apaixonada.",
    fundacao: "07-09-1913",
    estadio: "Estádio Rei Pelé",
    site_oficial: "https://www.csaoficial.com.br/",
    tags: "csa, centro sportivo alagoano, estádio rei pelé, futebol alagoano, serie c, campeonato alagoano, azul, branco",
    serie: "C",
    logo: "logos/csa.png",
  },
  {
    nome: "Confiança",
    descricao:
      "O Associação Desportiva Confiança é um dos clubes de destaque em Sergipe, com uma trajetória crescente no cenário nacional.",
    fundacao: "01-01-1968",
    estadio: "Estádio Batistão",
    site_oficial: "https://www.confiança.com.br/",
    tags: "confiança, confiança fc, estádio batistão, futebol sergipano, serie c, campeonato sergipano, azul, branco",
    serie: "C",
    logo: "logos/confi.png",
  },
  {
    nome: "Ferroviária",
    descricao:
      "A Associação Ferroviária de Esportes é um dos clubes tradicionais de São Paulo, com uma rica história de conquistas regionais.",
    fundacao: "01-01-1950",
    estadio: "Estádio Fonte Luminosa",
    site_oficial: "https://www.ferroviaria.com.br/",
    tags: "ferroviária, ferroviária, estádio fonte luminosa, futebol paulista, serie c, campeonato paulista, vermelho, branco",
    serie: "C",
    logo: "logos/fersp.png",
  },
  {
    nome: "Figueirense",
    descricao:
      "O Figueirense Futebol Clube é um dos clubes mais tradicionais de Santa Catarina, com uma rica história e uma torcida apaixonada.",
    fundacao: "12-06-1921",
    estadio: "Estádio Orlando Scarpelli",
    site_oficial: "https://www.figueirense.com.br/",
    tags: "figueirense, figueira, estádio orlando scarpelli, futebol catarinense, serie c, campeonato catarinense, preto, branco",
    serie: "C",
    logo: "logos/fig.png",
  },
  {
    nome: "Floresta",
    descricao:
      "O Floresta Esporte Clube é um dos clubes em ascensão no futebol cearense, com uma crescente presença nas competições nacionais.",
    fundacao: "23-01-2006",
    estadio: "Estádio Presidente Vargas",
    site_oficial: "https://www.florestaesporteclube.com.br/",
    tags: "floresta, floresta ec, estádio presidente vargas, futebol cearense, serie c, campeonato cearense, verde, branco",
    serie: "C",
    logo: "logos/flor.png",
  },
  {
    nome: "Ferroviário",
    descricao:
      "O Ferroviário Atlético Clube é um dos clubes mais tradicionais do futebol cearense, com uma rica história de conquistas regionais.",
    fundacao: "17-07-1933",
    estadio: "Estádio Castelão",
    site_oficial: "https://www.ferroviario.com.br/",
    tags: "ferroviário, ferroviário, estádio castelão, futebol cearense, serie c, campeonato cearense, vermelho, branco",
    serie: "C",
    logo: "logos/ferce.png",
  },
  {
    nome: "Londrina",
    descricao:
      "O Londrina Esporte Clube é um dos clubes de destaque no Paraná, com uma rica história de conquistas e uma torcida fiel.",
    fundacao: "05-04-1956",
    estadio: "Estádio do Café",
    site_oficial: "https://www.londrinaesporteclube.com.br/",
    tags: "londrina, londrina ec, estádio do café, futebol paranaense, serie c, campeonato paranaense, azul, branco",
    serie: "C",
    logo: "logos/lon.png",
  },
  {
    nome: "Náutico",
    descricao:
      "O Clube Náutico Capibaribe é um dos grandes clubes de Pernambuco, com uma rica história e uma torcida apaixonada.",
    fundacao: "07-04-1901",
    estadio: "Estádio dos Aflitos",
    site_oficial: "https://www.nautico-pe.com.br/",
    tags: "náutico, timbu, estádio dos aflitivos, futebol pernambucano, serie c, campeonato pernambucano, vermelho, branco",
    serie: "C",
    logo: "logos/nau.png",
  },
  {
    nome: "Remo",
    descricao:
      "O Clube do Remo é um dos clubes mais tradicionais do Pará, com uma rica história de conquistas e uma torcida apaixonada.",
    fundacao: "05-02-1905",
    estadio: "Estádio Baenão",
    site_oficial: "https://www.cluberemo.com.br/",
    tags: "remo, clube do remo, estádio baenão, futebol paraense, serie c, campeonato paraense, azul, branco",
    serie: "C",
    logo: "logos/remo.png",
  },
  {
    nome: "São Bernardo",
    descricao:
      "O São Bernardo Futebol Clube é um clube em ascensão no futebol paulista, com uma crescente presença nas competições nacionais.",
    fundacao: "01-01-2004",
    estadio: "Estádio 1º de Maio",
    site_oficial: "https://www.saobernardofc.com.br/",
    tags: "são bernardo, sbfc, estádio 1º de maio, futebol paulista, serie c, campeonato paulista, azul, branco",
    serie: "C",
    logo: "logos/saober.png",
  },
  {
    nome: "São José-RS",
    descricao:
      "O Esporte Clube São José é um dos clubes tradicionais do Rio Grande do Sul, com uma rica história no futebol gaúcho.",
    fundacao: "24-05-1913",
    estadio: "Estádio Passo D'Areia",
    site_oficial: "https://www.saojosefutebol.com.br/",
    tags: "são josé rs, são josé, estádio passo d'areia, futebol gaúcho, serie c, campeonato gaúcho, azul, branco",
    serie: "C",
    logo: "logos/saojo.png",
  },
  {
    nome: "Sampaio Corrêa",
    descricao:
      "O Sampaio Corrêa Futebol Clube é um dos clubes mais tradicionais do futebol maranhense, com uma rica história de conquistas regionais.",
    fundacao: "25-03-1923",
    estadio: "Estádio Castelão",
    site_oficial: "https://www.sampaiocorrea.com.br/",
    tags: "sampaio corrêa, sampaio, estádio castelão, futebol maranhense, serie c, campeonato maranhense, verde, branco",
    serie: "C",
    logo: "logos/samp.png",
  },
  {
    nome: "Tombense",
    descricao:
      "O Tombense Futebol Clube é um dos clubes em ascensão no cenário nacional, com uma crescente presença em competições.",
    fundacao: "01-06-1914",
    estadio: "Estádio Soares de Azevedo",
    site_oficial: "https://www.tombense.com.br/",
    tags: "tombense, tombense, estádio soares de azevedo, futebol mineiro, serie c, campeonato mineiro, vermelho, branco",
    serie: "C",
    logo: "logos/tom.png",
  },
  {
    nome: "Volta Redonda",
    descricao:
      "O Volta Redonda Futebol Clube é um dos clubes mais tradicionais do Rio de Janeiro, com uma história de destaque no futebol carioca.",
    fundacao: "09-02-1976",
    estadio: "Estádio Raulino de Oliveira",
    site_oficial: "https://www.voltaco.com.br/",
    tags: "volta redonda, voltaco, estádio raulino de oliveira, futebol carioca, serie c, campeonato carioca, amarelo, preto",
    serie: "C",
    logo: "logos/volta.png",
  },
  {
    nome: "Ypiranga-RS",
    descricao:
      "O Ypiranga Futebol Clube é um clube de destaque no Rio Grande do Sul, com uma história rica em competições regionais.",
    fundacao: "18-08-1924",
    estadio: "Estádio Colosso da Lagoa",
    site_oficial: "https://www.yfc.com.br/",
    tags: "ypiranga rs, ypiranga, estádio colosso da lagoa, futebol gaúcho, serie c, campeonato gaúcho, amarelo, verde",
    serie: "C",
    logo: "logos/ypi.png",
  },
  {
    nome: "São Raimundo",
    descricao:
      "O São Raimundo Esporte Clube é um dos clubes tradicionais de Roraima, com destaque nas competições regionais.",
    fundacao: "05-11-1982",
    estadio: "Estádio Ribeirão",
    site_oficial: "https://www.saoraimundo.com.br/",
    tags: "são raimundo, estádio ribeirão, futebol roraimense, serie d, campeonato roraimense, azul, branco",
    serie: "D",
    logo: "logos/saorai.png",
  },
  {
    nome: "Tocantinópolis",
    descricao:
      "O Tocantinópolis Futebol Clube é um dos clubes em ascensão no Tocantins, com destaque nas competições estaduais.",
    fundacao: "01-01-1994",
    estadio: "Estádio Ribeirão",
    site_oficial: "https://www.tocantinopolisfc.com.br/",
    tags: "tocantinópolis, tocantinópolis fc, estádio ribeirão, futebol tocantinense, serie d, campeonato tocantinense, verde, branco",
    serie: "D",
    logo: "logos/toca.png",
  },
  {
    nome: "Capital",
    descricao:
      "O Capital Futebol Clube é um dos clubes importantes do Tocantins, com uma trajetória crescente nas competições regionais.",
    fundacao: "01-01-2006",
    estadio: "Estádio General Sampaio",
    site_oficial: "https://www.capitalfc.com.br/",
    tags: "capital, capital fc, estádio general sampaio, futebol tocantinense, serie d, campeonato tocantinense, azul, branco",
    serie: "D",
    logo: "logos/capital.png",
  },
  {
    nome: "Cascavel",
    descricao:
      "O Cascavel Clube Recreativo é um dos clubes mais importantes do estado do Paraná, com destaque nas competições regionais.",
    fundacao: "10-12-1988",
    estadio: "Estádio Olímpico Regional",
    site_oficial: "https://www.cascavelcr.com.br/",
    tags: "cascavel, estádio olímpico regional, futebol paranaense, serie d, campeonato paranaense, verde, branco",
    serie: "D",
    logo: "logos/casca.png",
  },
  {
    nome: "Cianorte",
    descricao:
      "O Cianorte Futebol Clube é um clube emergente do Paraná, com crescente importância nas competições estaduais.",
    fundacao: "25-07-2000",
    estadio: "Estádio Albino Turbay",
    site_oficial: "https://www.cianortefc.com.br/",
    tags: "cianorte, estádio albino turbey, futebol paranaense, serie d, campeonato paranaense, azul, branco",
    serie: "D",
    logo: "logos/ciano.png",
  },
  {
    nome: "Maringá",
    descricao:
      "O Maringá Futebol Clube é um dos clubes mais tradicionais do estado do Paraná, com uma rica história nas competições estaduais.",
    fundacao: "18-03-1963",
    estadio: "Estádio Willie Davids",
    site_oficial: "https://www.maringafc.com.br/",
    tags: "maringá, estádio willie davids, futebol paranaense, serie d, campeonato paranaense, azul, branco",
    serie: "D",
    logo: "logos/marin.png",
  },
  {
    nome: "Avenida",
    descricao:
      "O Esporte Clube Avenida é um clube tradicional do Rio Grande do Sul, com uma longa história no futebol estadual.",
    fundacao: "06-09-1910",
    estadio: "Estádio dos Eucaliptos",
    site_oficial: "https://www.avenida.com.br/",
    tags: "avenida, estádio dos eucaliptos, futebol gaúcho, serie d, campeonato gaúcho, vermelho, branco",
    serie: "D",
    logo: "logos/ave.png",
  },
  {
    nome: "Brasil",
    descricao:
      "O Esporte Clube Brasil é um dos clubes mais tradicionais do Rio Grande do Sul, com destaque nas competições estaduais.",
    fundacao: "01-05-1911",
    estadio: "Estádio Bento Freitas",
    site_oficial: "https://www.ecbrasil.com.br/",
    tags: "brasil, estádio bento freitas, futebol gaúcho, serie d, campeonato gaúcho, vermelho, preto",
    serie: "D",
    logo: "logos/brasil.png",
  },
  {
    nome: "Novo Hamburgo",
    descricao:
      "O Esporte Clube Novo Hamburgo é um clube com uma rica história no futebol do Rio Grande do Sul e presença em competições regionais.",
    fundacao: "01-05-1911",
    estadio: "Estádio do Vale",
    site_oficial: "https://www.ecnh.com.br/",
    tags: "novo hamburgo, estádio do vale, futebol gaúcho, serie d, campeonato gaúcho, azul, branco",
    serie: "D",
    logo: "logos/novoham.png",
  },
  {
    nome: "Barra",
    descricao:
      "O Clube Atlético Barra é um clube de Santa Catarina, com uma trajetória em crescimento nas competições estaduais.",
    fundacao: "01-01-1990",
    estadio: "Estádio Lebon Régis",
    site_oficial: "https://www.barrafc.com.br/",
    tags: "barra, estádio lebon régis, futebol catarinense, serie d, campeonato catarinense, verde, branco",
    serie: "D",
    logo: "logos/barra.png",
  },
  {
    nome: "Concórdia",
    descricao:
      "O Concórdia Atlético Clube é um clube tradicional de Santa Catarina, com destaque nas competições estaduais.",
    fundacao: "08-12-1976",
    estadio: "Estádio Domingos Silveira Gonzales",
    site_oficial: "https://www.concordiafc.com.br/",
    tags: "concórdia, estádio domingos silveira gonzales, futebol catarinense, serie d, campeonato catarinense, azul, branco",
    serie: "D",
    logo: "logos/concor.png",
  },
  {
    nome: "Hercílio Luz",
    descricao:
      "O Hercílio Luz Futebol Clube é um dos clubes mais tradicionais de Santa Catarina, com uma rica história nas competições regionais.",
    fundacao: "14-05-1925",
    estadio: "Estádio Aníbal Costa",
    site_oficial: "https://www.hercilioluzfc.com.br/",
    tags: "hercílio luz, estádio aníbal costa, futebol catarinense, serie d, campeonato catarinense, vermelho, branco",
    serie: "D",
    logo: "logos/herci.png",
  },
  {
    nome: "Brasiliense",
    descricao:
      "O Brasiliense Futebol Clube é um dos clubes mais importantes do Distrito Federal, com uma rica história nas competições nacionais.",
    fundacao: "01-06-2000",
    estadio: "Estádio Nacional Mané Garrincha",
    site_oficial: "https://www.brasiliensefc.com.br/",
    tags: "brasiliense, estádio nacional mané garrincha, futebol do df, serie d, campeonato brasiliense, amarelo, verde",
    serie: "D",
    logo: "logos/brasili.png",
  },
  {
    nome: "Real Brasília",
    descricao:
      "O Real Brasília Futebol Clube é um dos clubes em crescimento no Distrito Federal, com destaque nas competições regionais.",
    fundacao: "01-01-2016",
    estadio: "Estádio Abadião",
    site_oficial: "https://www.realbrasilia.com.br/",
    tags: "real brasília, estádio abadião, futebol do df, serie d, campeonato brasiliense, vermelho, preto",
    serie: "D",
    logo: "logos/realfc.png",
  },
  {
    nome: "União",
    descricao:
      "O União Esporte Clube é um dos clubes tradicionais de Mato Grosso, com destaque nas competições regionais.",
    fundacao: "15-08-1957",
    estadio: "Estádio Luthero Lopes",
    site_oficial: "https://www.uniaoec.com.br/",
    tags: "união, estádio luthero lopes, futebol mato-grossense, serie d, campeonato mato-grossense, azul, branco",
    serie: "D",
    logo: "logos/uniao.png",
  },
  {
    nome: "Mixto",
    descricao:
      "O Mixto Esporte Clube é um dos clubes mais tradicionais de Mato Grosso, com uma rica história no futebol estadual.",
    fundacao: "09-07-1934",
    estadio: "Estádio Verdão",
    site_oficial: "https://www.mixtofc.com.br/",
    tags: "mixto, estádio verdão, futebol mato-grossense, serie d, campeonato mato-grossense, verde, branco",
    serie: "D",
    logo: "logos/mixto.png",
  },
  {
    nome: "Costa Rica",
    descricao:
      "O Costa Rica Futebol Clube é um clube de Mato Grosso do Sul, com destaque nas competições regionais.",
    fundacao: "18-08-1977",
    estadio: "Estádio Laertão",
    site_oficial: "https://www.costaricafc.com.br/",
    tags: "costa rica, estádio laertão, futebol sul-mato-grossense, serie d, campeonato sul-mato-grossense, azul, branco",
    serie: "D",
    logo: "logos/conta.png",
  },
  {
    nome: "Anápolis",
    descricao:
      "O Anápolis Futebol Clube é um dos clubes mais tradicionais de Goiás, com uma rica história nas competições estaduais.",
    fundacao: "01-01-1990",
    estadio: "Estádio Jonas Duarte",
    site_oficial: "https://www.anapolisfc.com.br/",
    tags: "anápolis, estádio jonas duarte, futebol goiano, serie d, campeonato goiano, azul, branco",
    serie: "D",
    logo: "logos/anapo.png",
  },
  {
    nome: "Crac",
    descricao:
      "O CRAC - Clube Recreativo e Atlético Catalano é um dos clubes de destaque em Goiás, com uma trajetória crescente.",
    fundacao: "03-02-1980",
    estadio: "Estádio Genervino da Fonseca",
    site_oficial: "https://www.crac.com.br/",
    tags: "crac, estádio genervino da fonseca, futebol goiano, serie d, campeonato goiano, verde, branco",
    serie: "D",
    logo: "logos/crac.png",
  },
  {
    nome: "Iporá",
    descricao:
      "O Iporá Esporte Clube é um clube em ascensão em Goiás, com destaque nas competições estaduais.",
    fundacao: "18-05-1992",
    estadio: "Estádio Ferreirão",
    site_oficial: "https://www.iporaec.com.br/",
    tags: "iporá, estádio ferreirão, futebol goiano, serie d, campeonato goiano, azul, branco",
    serie: "D",
    logo: "logos/ipora.png",
  },
  {
    nome: "ASA",
    descricao:
      "O ASA Futebol Clube é um dos clubes mais tradicionais de Alagoas, com uma rica história de conquistas regionais.",
    fundacao: "01-05-1952",
    estadio: "Estádio Coaracy da Mata Fonseca",
    site_oficial: "https://www.asafc.com.br/",
    tags: "asa, estádio coaracy da mata fonseca, futebol alagoano, serie d, campeonato alagoano, azul, branco",
    serie: "D",
    logo: "logos/asa.png",
  },
  {
    nome: "CSE",
    descricao:
      "O CSE - Centro Sportivo de Alagoas é um clube importante em Alagoas, com destaque nas competições regionais.",
    fundacao: "01-01-1960",
    estadio: "Estádio Juca Sampaio",
    site_oficial: "https://www.csealagoas.com.br/",
    tags: "cse, estádio juca sampaio, futebol alagoano, serie d, campeonato alagoano, vermelho, branco",
    serie: "D",
    logo: "logos/cse.png",
  },
  {
    nome: "Itabuna",
    descricao:
      "O Itabuna Esporte Clube é um dos clubes mais importantes da Bahia, com destaque nas competições estaduais.",
    fundacao: "28-08-1966",
    estadio: "Estádio Luiz Viana Filho",
    site_oficial: "https://www.itabunaec.com.br/",
    tags: "itabuna, estádio luiz viana filho, futebol baiano, serie d, campeonato baiano, azul, branco",
    serie: "D",
    logo: "logos/itabuna.png",
  },
  {
    nome: "Jacuipense",
    descricao:
      "A Associação Desportiva Jacuipense é um dos clubes tradicionais da Bahia, com uma rica história nas competições regionais.",
    fundacao: "01-01-2006",
    estadio: "Estádio Valfredão",
    site_oficial: "https://www.jacuipense.com.br/",
    tags: "jacuipense, estádio valfredão, futebol baiano, serie d, campeonato baiano, vermelho, branco",
    serie: "D",
    logo: "logos/jacuipa.png",
  },
  {
    nome: "Juazeirense",
    descricao:
      "O Juazeirense Futebol Clube é um dos clubes de destaque na Bahia, com uma trajetória crescente nas competições regionais.",
    fundacao: "01-01-2006",
    estadio: "Estádio Adauto Morais",
    site_oficial: "https://www.juazeirense.com.br/",
    tags: "juazeirense, estádio adauto morais, futebol baiano, serie d, campeonato baiano, vermelho, branco",
    serie: "D",
    logo: "logos/juaze.png",
  },
  {
    nome: "Atlético",
    descricao:
      "O Atlético Cearense é um dos clubes de destaque no Ceará, com uma trajetória crescente nas competições estaduais.",
    fundacao: "20-05-2008",
    estadio: "Estádio Domingão",
    site_oficial: "https://www.atleticocearense.com.br/",
    tags: "atlético, estádio domingão, futebol cearense, serie d, campeonato cearense, vermelho, branco",
    serie: "D",
    logo: "logos/atlece.png",
  },
  {
    nome: "Iguatu",
    descricao:
      "O Iguatu Futebol Clube é um dos clubes tradicionais do Ceará, com uma rica história nas competições regionais.",
    fundacao: "08-03-2008",
    estadio: "Estádio Agenorzão",
    site_oficial: "https://www.iguatufc.com.br/",
    tags: "iguatu, estádio agenorzão, futebol cearense, serie d, campeonato cearense, azul, branco",
    serie: "D",
    logo: "logos/igua.png",
  },
  {
    nome: "Maracanã",
    descricao:
      "O Maracanã Esporte Clube é um clube emergente do Ceará, com destaque nas competições regionais.",
    fundacao: "12-04-2004",
    estadio: "Estádio do Junco",
    site_oficial: "https://www.maracanacf.com.br/",
    tags: "maracanã, estádio do junco, futebol cearense, serie d, campeonato cearense, verde, branco",
    serie: "D",
    logo: "logos/maraca.png",
  },
  {
    nome: "Maranhão",
    descricao:
      "O Maranhão Atlético Clube é um dos clubes mais tradicionais do futebol maranhense, com uma rica história nas competições regionais.",
    fundacao: "02-09-1902",
    estadio: "Estádio Castelão",
    site_oficial: "https://www.maranhao.com.br/",
    tags: "maranhão, estádio castelão, futebol maranhense, serie d, campeonato maranhense, azul, branco",
    serie: "D",
    logo: "logos/maranhao.png",
  },
  {
    nome: "Moto Club",
    descricao:
      "O Moto Club de São Luís é um dos clubes mais tradicionais do futebol maranhense, com uma rica história nas competições regionais.",
    fundacao: "13-09-1938",
    estadio: "Estádio Castelão",
    site_oficial: "https://www.motoclub.com.br/",
    tags: "moto club, estádio castelão, futebol maranhense, serie d, campeonato maranhense, vermelho, preto",
    serie: "D",
    logo: "logos/moto.png"
  },
  {
    nome: "Souza",
    descricao:
      "O Souza Esporte Clube é um dos clubes em ascensão na Paraíba, com destaque nas competições regionais.",
    fundacao: "01-01-2003",
    estadio: "Estádio Marizão",
    site_oficial: "https://www.souzaec.com.br/",
    tags: "souza, estádio marizão, futebol paraibano, serie d, campeonato paraibano, verde, branco",
    serie: "D",
    logo: "logos/souza.png",
  },
  {
    nome: "Treze",
    descricao:
      "O Treze Futebol Clube é um dos clubes tradicionais da Paraíba, com uma rica história de conquistas regionais.",
    fundacao: "07-09-1925",
    estadio: "Estádio Amigão",
    site_oficial: "https://www.trezefc.com.br/",
    tags: "treze, estádio amigão, futebol paraibano, serie d, campeonato paraibano, vermelho, branco",
    serie: "D",
    logo: "logos/treze.png",
  },
  {
    nome: "Petrolina",
    descricao:
      "O Petrolina Social Futebol Clube é um dos clubes em ascensão na Bahia, com destaque nas competições estaduais.",
    fundacao: "01-01-1997",
    estadio: "Estádio Paulo Coelho",
    site_oficial: "https://www.petrolina.com.br/",
    tags: "petrolina, estádio paulo coelho, futebol baiano, serie d, campeonato baiano, azul, branco",
    serie: "D",
    logo: "logos/petro.png",
  },
  {
    nome: "Retrô",
    descricao:
      "O Retrô Futebol Clube Brasil é um clube emergente na Bahia, com uma crescente presença nas competições estaduais.",
    fundacao: "01-01-2014",
    estadio: "Estádio Eládio de Barros Carvalho",
    site_oficial: "https://www.retrofc.com.br/",
    tags: "retrô, estádio eládio de barros carvalho, futebol baiano, serie d, campeonato baiano, azul, branco",
    serie: "D",
    logo: "logos/retro.png",
  },
  {
    nome: "Altos",
    descricao:
      "O Altos Futebol Clube é um dos clubes em ascensão no Piauí, com destaque nas competições regionais.",
    fundacao: "01-01-2011",
    estadio: "Estádio Felipe Santiago",
    site_oficial: "https://www.altosfc.com.br/",
    tags: "altos, estádio felipe santiago, futebol piauiense, serie d, campeonato piauiense, verde, branco",
    serie: "D",
    logo: "logos/altos.png",
  },
  {
    nome: "4 de Julho",
    descricao:
      "O 4 de Julho Esporte Clube é um clube tradicional no Piauí, com uma rica história nas competições regionais.",
    fundacao: "01-01-1995",
    estadio: "Estádio Albertão",
    site_oficial: "https://www.4dejulhoec.com.br/",
    tags: "4 de julho, estádio albertão, futebol piauiense, serie d, campeonato piauiense, vermelho, branco",
    serie: "D",
    logo: "logos/4jul.jpeg",
  },
];
